version: "3"

networks:
  network_atelier:
    driver: bridge

services:
  service_auth:
    container_name: service_auth
    image: node
    ports:
      - "62349:3000"
    volumes:
      - ./service_auth:/app
    working_dir: /app
    env_file:
      - ./.env
    command: bash -c 'npm i && npm run dev'
    depends_on:
      - iut_db_atelier
    networks:
      - network_atelier

  service_events:
    container_name: service_events
    image: node
    ports:
      - "62345:3002"
    volumes:
      - ./service_events:/app
    working_dir: /app
    env_file:
      - ./.env
    command: bash -c 'npm i && npm run dev'
    depends_on:
      - iut_db_atelier
    networks:
      network_atelier:
        aliases: 
          - service.events

  service_gateway:
    container_name: service_gateway
    image: node:lts
    env_file: ./.env
    working_dir: /app
    volumes:
      - ./service_gateway:/app
    ports:
      - 62346:3001
    command: bash -c 'npm i && npm run dev'
    depends_on:
      - iut_db_atelier
      - service_events
      - service_auth
    links: 
      - service_events
    networks:
      - network_atelier

  iut_db_atelier:
    container_name: iut_db_atelier
    image: mariadb:latest
    env_file: ./.env
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql/script_db_reunionou.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - network_atelier

  atelier_adminer:
    container_name: atelier_adminer
    image: adminer
    ports:
      - 62340:8080
    depends_on:
      - iut_db_atelier
    networks:
      - network_atelier

  atelier_php_my_admin:
    container_name: atelier_php_my_admin
    image: phpmyadmin:latest
    # links: 
    #   - iut_db_atelier
    environment:
      PMA_HOST: iut_db_atelier
      PMA_PORT: 3306
    ports:
      - 62347:80
    depends_on:
      - iut_db_atelier
    networks: 
      - network_atelier