-- MySQL Script generated by MySQL Workbench
-- Mon Mar 21 11:48:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_reunionou
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_reunionou
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_reunionou` DEFAULT CHARACTER SET utf8 ;
USE `db_reunionou` ;

-- -----------------------------------------------------
-- Table `db_reunionou`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reunionou`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NULL,
  `email` VARCHAR(255) NULL,
  `password` LONGTEXT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `last_connection` DATETIME NULL,
  PRIMARY KEY (`id_user`));


-- -----------------------------------------------------
-- Table `db_reunionou`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reunionou`.`events` (
  `id_events` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(32) NULL,
  `address` VARCHAR(16) NULL,
  `localisation` VARCHAR(45) NULL,
  `token` VARCHAR(16) NULL,
  `date_events` DATETIME NULL,
  `last_update` DATETIME NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_events`),
  INDEX `fk_events_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_events_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `db_reunionou`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reunionou`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reunionou`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `events_id_events` INT NOT NULL,
  `text` VARCHAR(45) NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_comment`, `user_id_user`),
  INDEX `fk_comment_events1_idx` (`events_id_events` ASC),
  INDEX `fk_comment_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_comment_events1`
    FOREIGN KEY (`events_id_events`)
    REFERENCES `db_reunionou`.`events` (`id_events`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `db_reunionou`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reunionou`.`events_annex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reunionou`.`events_annex` (
  `id_events_annex` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(32) NULL,
  `present` BINARY NULL,
  `date_at` DATETIME NULL,
  `user_id_user` INT NULL,
  `events_id_events` INT NOT NULL,
  PRIMARY KEY (`id_events_annex`),
  INDEX `fk_events_annex_user1_idx` (`user_id_user` ASC),
  INDEX `fk_events_annex_events1_idx` (`events_id_events` ASC),
  CONSTRAINT `fk_events_annex_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `db_reunionou`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_annex_events1`
    FOREIGN KEY (`events_id_events`)
    REFERENCES `db_reunionou`.`events` (`id_events`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_reunionou`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_reunionou`.`admin` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_admin`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- INSERT events
-- -----------------------------------------------------

INSERT INTO events (title,address,localisation,token,date_events,last_update,user_id_user)
VALUES
  ("rdv_jean anniversaire_Papy","452-4263 Est, Rd.","32.5969645568, -111.7979297792","UIE14MEN6WH","2021-11-12 00:00:00","2021-10-07 00:00:00",1),
  ("anniversaire_mami anniversaire_Laure","261-866 Nisl Rd.","-67.7927790592, -82.838011904","FWG76WMO2EK","2022-11-27 00:00:00","2022-02-13 00:00:00",2),
  ("rdv_jean anniversaire_Papy","Ap #788-4284 Gravida St.","42.9407051776, 147.9463177216","WUW82PHK5SW","2021-10-07 00:00:00","2021-07-21 00:00:00",1),
  ("anniversaire_mami anniversaire_Laure","614-8982 Massa Av.","83.1886403584, -7.3505230848","LJS66OMP5MM","2022-11-13 00:00:00","2021-06-25 00:00:00",3),
  ("rdv_arthure rdv_jean","707-8926 Eu, Street","69.261202944, -77.6789656576","XXO18TJE1QP","2022-10-01 00:00:00","2022-04-14 00:00:00",2);